### PR TITLE
attempt at a fix for the rooted flag

### LINKED ISSUE #90: rooted flag exposes serialization ambiguity
This should not be possible:
```
>>> import hyperlink
>>> a = hyperlink.URL(path=['', 'foo'], rooted=False)
>>> b = hyperlink.URL(path=['foo'], rooted=True)
>>> a == b
False
>>> a
URL.from_text('/foo')
>>> b
URL.from_text('/foo')
>>> a.normalize() == b.normalize()
False
```
I think that if `path` ever starts with a `''` when `rooted=False`, we ought to flip the flag and remove the path segment.

### PR DESCRIPTION
**Pull request by glyph**
Fixes #90

### CODE REVIEW

**Comment by glyph** [comment]
@wsanchez @mahmoud anybody up for a review

**Comment by wsanchez** [comment]
This looks fine to me, given the way the code works now, but I guess I don't understand why `rooted` is an argument to `URL` in the first place.

Shouldn't it just be a computed (perhaps cached) property instead of a user-defined attribute?

**Comment by wsanchez** [comment]
I guess my question is really just aspirational; the API is what it is.

**Comment by glyph** [comment]
> I guess my question is really just aspirational; the API is what it is.

I think the question still deserves answering, since this API is *super* subtle.  The main thing I'd say about this is that it does make a lot more sense than attempting to deal with nonsensical values for `path`, but still always get the right number of slashes, and not use different data structures for relative and absolute URLs.

**Pull request merged**
