### PR TITLE
GitHub Actions CI

### PR DESCRIPTION
**Pull request by twm**
Travis is queuing builds for ages. 

I've also added Python 3.9 to CI and the package metadata. I notice that 2.6 isn't in CI. Should it still be listed as supported?

### CODE REVIEW

**Comment by wsanchez** [comment]
Hrm, I think we should add 2.6 to the matrix. That does seem like an oversight…
We bend over a bit to support 2.6 syntax, so it should be tested.

**Comment by wsanchez** [comment]
I'm not seeing the workflows running… is that because this is an external PR and not a branch?

**Comment by twm** [comment]
I honestly don't know. GHA is not great with the feedback... if you typo something in the YAML it doesn't tell you so it could be anything. I'll try creating a separate PR that's more obviously correct.

**Comment by twm** [comment]
Nothing seems to be happening on #143, so I guess I can't configure GHA from my fork.

**Comment by wsanchez** [comment]
@twm I'm getting ready for some travel this week but when I'm back in California, I can try making a branch with this and see if that works.

**Comment by wsanchez** [comment]
@twm I added you as an admin to the repo, so you should be able to make a branch with this diff if you can get to it before me.

**Comment by twm** [comment]
Thanks @wsanchez. I've recreated this PR over at #149. Closing this one in favor of that one, where GHA seems to be working.

**Pull request closed without merging**
